### ISSUE TITLE
GSI failed to pass integrity and CTS

### ISSUE THREAD

**Issue by Chuanhuan** [VegaBobo/DSU-Sideloader#121]
After I downloaded google GSI+GMS  and lPixel Experience Plus. I install YASNAC and I found this rom and google GSI+GMS ROM after install via DSU-sideloader root method. Both are not passed the basic integrity! 

My company also has app can detect root status.Suddenly I also see the magisk in app drawer.
I install Magisk Hide Props Config and SafetyNet, then passed basic integrity. However, because mine is tab s8 plus. I can't find in custom devices list. 
Just curious is all GSI ROM have magisk in order to boot to DSU? Is any easy way to pass integrity and CTS

**Comment by VegaBobo** [comment]
If your original OS is rooted via Magisk, then any GSI you boot via DSU are likely to be also rooted¹, Magisk is commonly installed in one of the "initialization" partitions of device (in most cases, the "boot" partition), since boot partition isn't replaceable by DSU, when booting a installed DSU, it should keep using the current "boot" partition, if that partition contains a Magisk installation, then it should also bring root to installed DSU.

¹ Some GSIs may come pre-rooted, in those cases, root solutions may conflict, which may cause errors, including not being able to use some of the root solutions, or none of them at all.

About other problems, well, they aren't really to do with this app at all, our goal was reached, which is to install images using DSU feature.
