### ISSUE TITLE
Custom Boot Images

### ISSUE THREAD

**Issue by sounddrill31** [VegaBobo/DSU-Sideloader#122]
Is it possible to run the GSI with a custom boot image in the future? It would be really useful as it would allow halium, for example, to function, allowing dual booting android and linux mobile(droidian, ubports UT, etc)

I read about this person [who tried to do the same with a custom vendor partition](https://github.com/VegaBobo/DSU-Sideloader/issues/93). I wonder if it is already possible!

**Comment by VegaBobo** [comment]
I didn't tested or even searched it further, so i might be wrong, but i think that isn't possible, in Android docs (https://source.android.com/docs/core/ota/dynamic-system-updates#multiple-partition-dsu ), "_When the device boots, the first stage init detects the installed DSU partitions and replaces the on-device partition temporarily_",  i think that isn't possible because DSU partition "swap" occurs when boot partition is already initialized, since those actions occurs on first stage init.

**Comment by sounddrill31** [comment]
> I didn't tested or even searched it further, so i might be wrong, but i think that isn't possible, in Android docs (https://source.android.com/docs/core/ota/dynamic-system-updates#multiple-partition-dsu ), "_When the device boots, the first stage init detects the installed DSU partitions and replaces the on-device partition temporarily_", i think that isn't possible because DSU partition "swap" occurs when boot partition is already initialized, since those actions occurs on first stage init.

Shame, thanks a whole lot for reading and responding!
