### ISSUE TITLE
file permission errors on hisense firmware

### ISSUE THREAD

**Issue by JanglePlatformTeam** [VegaBobo/DSU-Sideloader#13]
Hey all as stated in title on the hisense q5 I'm receiving some sort of a file error when trying to use this app.
`3-08 16:23:35.520 11667 11669 E gsid    : failed to create or open /data/gsi/dsu/userdata_gsi.img
03-08 16:23:35.520 11667 11669 E gsid    : Could not create userdata image: /data/gsi/dsu/userdata_gsi.img
03-08 16:23:35.397 12192 12192 I chatty  : uid=1000(system) com.hmct.eye.remind identical 12 lines
03-08 16:23:35.461 12192 12192 D EyeReminding: light can not show!
03-08 16:23:35.522 12498 12523 W System.err: java.io.IOException: Failed to start installation with requested size: 6964084736
03-08 16:23:35.523 12498 12523 W System.err:    at com.android.dynsystem.InstallationAsyncTask.doInBackground(InstallationAsyncTask.java:130)
03-08 16:23:35.523 12498 12523 W System.err:    at com.android.dynsystem.InstallationAsyncTask.doInBackground(InstallationAsyncTask.java:36)
03-08 16:23:35.523 12498 12523 W System.err:    at android.os.AsyncTask$3.call(AsyncTask.java:378)
03-08 16:23:35.523 12498 12523 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-08 16:23:35.523 12498 12523 W System.err:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
03-08 16:23:35.523 12498 12523 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-08 16:23:35.523 12498 12523 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-08 16:23:35.523 12498 12523 W System.err:    at java.lang.Thread.run(Thread.java:919)
03-08 16:23:35.523 12498 12498 D InstallationAsyncTask: onPostExecute(), URL: file:///storage/emulated/0/Download/workspace_dsuhelper/system-squeak-arm64-ab-gapps.img.gz, result: 2`

**Comment by VegaBobo** [comment]
DSU feature seems broken in your current ROM.
Are you running Android 10? if so, try set selinux to permissive, and try again.

**Comment by JanglePlatformTeam** [comment]
I attempted setting selinux to permissive and seem to get a slightly diff error, attached is the whole log. [logcat_dsu.txt](https://github.com/VegaBobo/DSU-Sideloader/files/8248180/logcat_dsu.txt)

**Comment by VegaBobo** [comment]
You're using Android 10, right?
Android 10 seems to have this bug, fortunately it was fixed on 11, however people running Android 10 seem to be "out of luck".
I tried to fix this issue by building a custom gsid with some patches from Android 11, however, i do not have a Android 10 device to test it :\

Anyway, what Android version you're running? do you have Magisk installed? if so, i can send create a module with a custom gsid binary that may fix your issue (no clue if it will work)

**Comment by JanglePlatformTeam** [comment]
No magisk but a userdebug build, currently trying to livepatch in a magisk
su bin, though after further investigation and a conversation with unisoc
it seems they may have intentionally disabled the gsi functions in their
code.

**Comment by VegaBobo** [comment]
Thats sad, anyway, i got a unisoc device running Android 10, and i got the same problems as you, after setting selinux to permissive, dsu just finishes silently with extents error, when using a custom gsid binary (the one i've did some changes), installation process works and finishes as well, but i cannot test if dsu is really working, because im running on locked bootloader (those unisoc seem hard to unlock without manufacture help).

If you, or someone else wants to try, ill be linking a Magisk Module (if no Magisk is avaiable, you can replace gsid binary directly into system partition, binary is inside module) [module_gsid_test.zip](https://github.com/VegaBobo/DSU-Sideloader/files/8599771/module_gsid_test.zip)

About the changes, i've just compiled Android 10 with this:
https://android-review.googlesource.com/c/platform/system/gsid/+/1166406/

No clue if it will work, make sure to do a backup first, also, i have no idea what can go wrong, so keep caution!

<img src="https://user-images.githubusercontent.com/42748890/166165098-cb671634-ac3b-4ab0-af86-24c2d0453417.png" width="200">

**Comment by VegaBobo** [comment]
Ill be closing this as completed, DSU Sideloader v2 includes a Magisk module that adds a custom gsid binary, in which, may fix this Android 10 issue, i've tested installation, and seems to be working as expected (i cannot test if installation was really working because the unique device i have to test it, was one with locked bootloader).

**Comment by srihari0-0** [comment]
Is there any way to install that custom magisk module without root or any other way around. Sorry, I am new to this and i want to install this module but i don't want to root my device. I found this comment from another forum _  " if no Magisk is avaiable, you can replace gsid binary directly into system partition, binary is inside module) ". Can someone explain what it means.{ i have unlocked bootloader of my device  and is running dsu in shizuku mode}
