### ISSUE TITLE
Install fails when I manually set userdata. 

### ISSUE THREAD

**Issue by XDanfr** [VegaBobo/DSU-Sideloader#131]
What it says on top
[logs.txt](https://github.com/VegaBobo/DSU-Sideloader/files/12784982/logs.txt)

**Comment by VegaBobo** [comment]
Can you confirm if it works when you don't set? I've saw some of those errors before, but they happen anyway, setting or not

**Comment by XDanfr** [comment]
Yes, when I don't change userdata size it works perfectly, but if I change it then change it back to the default it doesn't work and requires me to reset my phone. I ended up using a gsi by flashing to system partition in the end tho :)

**Comment by VegaBobo** [comment]
Good then, anyway, since you ended up flashing GSI into your system partition, that means your main OS is the installed GSI, so keep in mind you can still use DSU Sideloader to test other GSI images, i think the problem you have been experiencing may be related to size, the default userdata is 2GB, so, maybe setting a lower userdata value may fix your problem, anyway, ill be closing it, feel free to open other issues if you think so, and sorry for late answer, pretty busy :\
