### ISSUE TITLE
Crashing after selecting an image

### ISSUE THREAD

**Issue by TimmyTurner51** [VegaBobo/DSU-Sideloader#135]
Hello, I need to figure out if it's possible to get logs to help more with this issue, I can't see what's wrong. But when it opens file picker and tap an image, it just crashes. It's not an issue with the rom as every rom did this. The rom worked before on the phone until I reset everything and rooted with Magisk Delta. Even switched over to regular Magisk but it still crashes.

**Comment by VegaBobo** [comment]
Since it is an app crash, you can get the logs from the crash by:
1. Install and open Termux (or any terminal emulator, if you have PC with ADB, you can use adb shell instead)
2. Run "su" command (so we can run command as root)
3. Run "logcat -c" command (to clean old logs)
4. Run "logcat > /sdcard/logs.logcat"  command (runs logcat, and send the outputs of this command to /sdcard/logs.logcat)
5. Open DSU Sideloader and crash it
6. Go back to terminal emulator, press keys CTRL + C (to cancel)
7. You will have a file inside your internal storage, called "logs.logcat"
8. Send those logs here, so i can diagnose

**Comment by TimmyTurner51** [comment]
It seemed to have fixed itself. Not sure if flashing persist image did the trick or not. If I ever have the issue again, I'll be sure to make that log.

**Comment by VegaBobo** [comment]
Ill mark this as completed, but feel free to open other issues if you think so, thanks!
