### ISSUE TITLE
[Question] using DSU with locked bootloader

### ISSUE THREAD

**Issue by LeOS-GSI** [VegaBobo/DSU-Sideloader#160]
Hi,
I know, that your sideloader is needing an open bootloader. But on my ViVo with A13, I can't unlock the bootloader. Do you now any way to run my GSI with DSU sideloader ? 
The stupid thing is, the ViVo OS doesn't have standard DSU in developer options :(

Would be great if you could help me. 

(I have tried, but the installed GSI is not booting. After OEM logo, the screen is getting black and then it is reboot into OEM firmware?

**Comment by VegaBobo** [comment]
When you start your device on locked bootloader, verified boot will verify what OS is booting, if that OS isn't considered trusted, it will refuse to boot, fortunately/unfortunately, in most cases, the only OS considered trusted, are the ones signed by OEM, so, i guess if you can sign a GSI using OEM private keys, you might me able to boot it with locked bootloader? anyway, obtaining that is almost impossible for most of us, so not a practical option :\

Some doc links:
https://source.android.com/docs/security/features/verifiedboot/device-state#root-of-trust
https://source.android.com/docs/security/features/verifiedboot/boot-flow

Unfortunately, i think unlocking the bootloader is the unique viable option, in some cases, there are some alternative ways to unlock bootloader, like mtkclient (can unlock some MTK devices), PotatoNV (can unlock some Huawei/Honor), CVE-2022-38694 (should be able to unlock some Unisoc SoC devices).

**Comment by LeOS-GSI** [comment]
Thx for answer / clarification. The Problem is, that there is no way to unlock bootloader on newer ViVo devices :/

**Comment by acastillorobles77** [comment]
I have the same question. However, instead of loading a third-party GSI, I'd like to know if is possible to load my current system image extracted from my currrent firmware on a locked bootloader. In theory, this should pass the requierement of the image needed to be sign by the OEM (in my case, OPPO, model CPH2599). My only intention of doing this is to get an isolated environment on my phone, but I'm scared to try this myself because something could go wrong. Would something like this work? Has anyone tried this before, and succeeded?
