### ISSUE TITLE
40% check

### ISSUE THREAD

**Issue by IMgoRt** [VegaBobo/DSU-Sideloader#19]
I have a 256gb phone and am at 60% usage so this app won't load
What's the logic behind the 40% test?

Thanks

**Comment by VegaBobo** [comment]
Android's gsid checks for 40% of available storage, if it dosent have, then, DSU will fail on installation process, so, i've made this check on app, to avoid time loss.
As you can see [here](https://cs.android.com/android/platform/superproject/+/android-12.1.0_r5:system/gsid/partition_installer.cpp;l=135)

Anyway, probably on future ill be creating a option to ignore this dialog, since is possible to change this behavior on a custom build.
