### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by Kat0P2003** [VegaBobo/DSU-Sideloader#4]
would it be possible to use the sd card storage instead of the internal memory?

**Comment by VegaBobo** [comment]
DSU Sideloader invokes DSU installation activity, with parameters you have set on app.

By default, DSU gives allocation priority to SD card (when present), as you can see here: https://source.android.com/devices/tech/ota/dynamic-system-updates#hardware-requirements

However, this may vary by OEM, since i've tested DSU mainly on my Moto G30, and even with SD card present, it always allocate on internal storage.
So, by now, it probably depends on your device.

If is possible to force allocation on sd or internal, i don't know, it needs some research (that i will probably do in future).
