### ISSUE TITLE
ADB Command Now Working - Fixed

### ISSUE THREAD

**Issue by theghostkill** [VegaBobo/DSU-Sideloader#54]
Given adb command in the app -
`adb shell ' sh "/storage/emulated/0/GSI/workspace_dsuhelper/install" '`

this gives error
`/system/bin/sh:  sh /storage/emulated/0/GSI/workspace_dsuhelper/install : inaccessible or not found`

Removing ' worked. Command -
`adb shell sh "/storage/emulated/0/GSI/workspace_dsuhelper/install"`

> Device Information:
> Samsung A52s 5G
> OneUI 5.0 (Android 13)
> API 33

**Comment by VegaBobo** [comment]
Single quotes with double quotes have been used to escape some characters, since user can setup a folder on first application startup that may contain special characters, which can cause "syntax error".
Anyway, using double quotes with single quotes was a lazy solution, installation script will be now moved to a proper folder that is unlikely to cause these issues.
