### ISSUE TITLE
Crash while setting up storage directory

### ISSUE THREAD

**Issue by firedevel** [VegaBobo/DSU-Sideloader#55]
I'm trying to install gsi on my mitv, it has no navbar and DocmentUI app, so i tried this app.
I chose root mode and normally it should have all the permissions, right?
I just clicked ”设定“

![screen](https://user-images.githubusercontent.com/70802618/211033812-9895cf42-609c-4042-a88d-f31fba1f4d5f.png)

I guess a log file may be needed to fix this, but I don't know how to get it.

**Comment by VegaBobo** [comment]
Unfortunately DSU Sideloader rely on DocumentsUI to do a lot of stuff, like setting up the folder, file picker and some other operations, since your Android implementation doesn't include DocumentsUI, it won't work as expected, even with root or other operation mode.
Support for devices without DocumentsUI is not planned, since most devices includes it already, maybe we bring support for this in future, but i cannot promise you anything.

Anyway, you can still install images using command line, check Android documentation: https://developer.android.com/topic/dsu
