### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ilhmnnda** [VegaBobo/DSU-Sideloader#58]
[logs (1).txt](https://github.com/VegaBobo/DSU-Sideloader/files/10521810/logs.1.txt)

I've always fail to install gsi using dsu, at first it was fine i can install 5+ gsi without issue. But now it's keep fail and even I've install the same gsi that works before now it doesn't work anymore

Also I used only apk first but now using the magisk module also doesn't do anything

Edit : I'm sorry i think it's because my storage. I just removed something from 16gbs to 23gbs and now it's started to work again. But i have question how much storage i need because i only have 64gb model

**Comment by VegaBobo** [comment]
Yes, you need a considerable amount of storage to install images, the error in your logs are because of lacking free storage, the storage you need may vary from:
 - Images you're trying to install (since the file itself weights something).
 - Allocation (images might be allocated in sdcard when supported).
 - Chosen file and installation method (since chosen file may be not "direct installable", thus, needing to be decompressed or compressed, which may take some storage).
 - How much userdata storage you set in application (default is 2G, but you can set a custom value)
 
Anyway, Android recommends at least reserving 10G of free space: https://source.android.com/docs/core/ota/dynamic-system-updates#hardware-requirements
