### ISSUE TITLE
Can explain a litle more about "creating new partitions"

### ISSUE THREAD

**Issue by Mitezuss** [VegaBobo/DSU-Sideloader#61]
I don't know if this is a place to ask about, but on your text:

_"this is done by creating new partitions to hold a GSI and a separated userdata"_

I wanna know:

1. Where ? (on partition B ? or same partition of system ? (partition A) or en Super partition ?)
2. How many partitions ?
3. What happen after "reboot" ? (are deleted?)

Thanks

**Comment by LeOS-GSI** [comment]
1. DSU will create all needed partition in your userdata partition
2. not sure, but I think it 'system' / 'userdata' / 'kernel ?'
3. It depends on your decision. Boot into new GSI or you base system. The folder with the created DSU partitions are existing til you delete them

**Comment by VegaBobo** [comment]
Where? 
In files, DSU priorizes allocation in SD card, if not available or not supported, they will be allocated in userdata, you can check where installation happens in logs (commonly they are in /data/gsi/dsu when allocation happens in userdata).
For reference: https://source.android.com/docs/core/ota/dynamic-system-updates#hardware-requirements
```
cool logs message ok:
lmi:/ # logcat | grep /data/gsi
03-18 19:07:47.520  1901  4841 I DynamicSystemService: startInstallation -> /data/gsi/dsu
03-18 19:07:47.923  9948  9956 I gsid    : Created loop device /dev/block/loop45 for file /data/gsi/dsu/userdata_gsi.img.0000
03-18 19:07:48.483  9948  9956 I gsid    : Created loop device /dev/block/loop45 for file /data/gsi/dsu/system_gsi.img.0000
03-18 19:08:15.103  9948  9956 I gsid    : Created loop device /dev/block/loop45 for file /data/gsi/dsu/scratch_gsi.img.0000

```

How many partitions?
Android 10, i think only userdata and system.
Android 11 and higher, most partitions besides somes that are initialized before DSU can replace them, which include some that are hardcoded to be not replaced in installation time.
Most GSIs are only a single image, which means only two partitions are replaced, userdata and system, but you can replace multiple by using DSU packages (eg: system, product, vendor...)
For reference: https://source.android.com/docs/core/ota/dynamic-system-updates#multiple-partition-dsu
Unsupported partitions: https://cs.android.com/android/platform/superproject/+/android-13.0.0_r31:frameworks/base/packages/DynamicSystemInstallationService/src/com/android/dynsystem/InstallationAsyncTask.java;l=71
** as told before, partitions like userdata and scratch are in the list of unsupported partitions, because they haven't made to be replaced at installation time, since those partitions will be created instead.
** those unsupported partitions are also unsupported by DSU Sideloader built-in installer: https://github.com/VegaBobo/DSU-Sideloader/blob/master/app/src/main/java/vegabobo/dsusideloader/installer/root/DSUInstaller.kt#L72

What happen after reboot?
After installing a GSI via DSU, a notification will show up in your device, called "Dynamic System Updates", with this notification you can control the installed DSU state, you can reboot, which will reboot your device into installed images, or discard them, which delete installed images and remove installed DSU.
If you decide to reboot into installed DSU, your device will boot into installed images only once, which means if you reboot device again, next boot will start your device into original OS, this action is called "oneshot", and is the default behavior of DSU, once you are back into your original OS, the "Dynamic System Updates" notification will show up again, and you can chose what do to, reboot into DSU again, or discard it!
If you want to keep booting into installed DSU instead of your original OS, you can enable "sticky mode", that will do the intended behavior.
