### ISSUE TITLE
Official dsu apis

### ISSUE THREAD

**Issue by giuliofini08** [VegaBobo/DSU-Sideloader#96]
Is this app made using the official dsu apis descrived in source.android.com?

**Comment by VegaBobo** [comment]
This app has some operation modes:
- ADB: default operation mode when other modes aren't available, which basically prepare selected image and craft a proper shell command to install images using DSU system app, similar behavior to this: https://developer.android.com/topic/dsu#command-line, images will be installed via DSU system app.
- Shizuku: when using app with shizuku permissions granted, similar behavior as ADB, however, we can use some APIs as shell authority, so we can invoke DSU installation activity without relying on shell commands, which also support other features, like logcat logging for debugging installation and other stuff, images will be installed via DSU system app.
- System: when running as system app by installing DSU Sideloader module, system works the same as Shizuku, but doesn't require Shizuku itself, module proporse was to fix some common installation errors, anyway, images will be installed via DSU system app.
- Root: when running with granted root permissisons, has same features as Shizuku operation mode, with some extras, since as root we can have MANAGE_DYNAMIC_SYSTEM permission, by default, images will be installed via DSU system app, however, there is a built-in installer option, which uses a in-app DSU installer, which will use Dynamic System APIs to install images: https://github.com/VegaBobo/DSU-Sideloader/blob/master/app/src/main/java/vegabobo/dsusideloader/installer/root/DSUInstaller.kt#L42

There is also a System/Root mode, that will combine features from root and system operation mode.

**Comment by rokejulianlockhart** [comment]
Thanks lots, but is that a yes?
